/**
 * geminiService.js — Google Gemini AI Integration for CareerPath AI
 * Powers the AI Career Mentor & Doubt Solver
 * CareerPath AI · Enterprise Backend Service
 */

const SYSTEM_PROMPT = `You are CareerPath AI Mentor, an empathetic, encouraging, and expert technical career counselor embedded inside the student's learning portal.
Your mission is to provide structured, student-friendly, and actionable tech career guidance to college students and freshers.

FORMATTING & STRUCTURE RULES (STUDENT PORTAL FRIENDLY):
Structure every response cleanly using Markdown with these student-focused sections:

1. 🎯 **Key Takeaway**: 1-2 direct, encouraging sentences immediately answering the student's question.
2. 📌 **Action Plan**: Numbered step-by-step roadmap (e.g. 1., 2., 3.) with specific tools, frameworks, and practical milestones.
3. > 💡 **Pro-Tip**: A highlighted callout with industry insider advice that college professors rarely teach.
4. 🛠️ **Recommended Tech Stack / Practice**: 3-5 high-demand technologies, tools, or practice topics.
5. 🚀 **Portal Quick Action**: Remind the student where in this portal they can apply this:
   - [My Roadmap](roadmap.html) to track weekly curriculum tasks
   - [Skill Assessment](assessment.html) to test and verify skills
   - [ATS Resume Studio](resume-builder.html) to optimize their resume
   - [Job Market](jobs.html) to check live hiring demand

TONE & STYLE:
- Empathetic, motivating, structured, and practical.
- Avoid overwhelming walls of unstructured text. Keep answers crisp (150-250 words unless asked for a complete syllabus).
- If the student asks in Hinglish (Hindi + English), reply warmly in natural Hinglish/English mix.
- Tailor guidance directly to the student's degree, target career, and current skills provided in context.`;

const GEMINI_MODELS = [
  process.env.GEMINI_MODEL,
  'gemini-2.0-flash',
  'gemini-1.5-flash',
  'gemini-1.5-pro'
].filter(Boolean);

let isGeminiDisabled = false;

async function callGemini(contents, model = null, signal, customSystemPrompt = null) {
  if (isGeminiDisabled) {
    throw new Error('Gemini engine is disabled due to invalid API key.');
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not configured in server environment.');
  }

  // 2.5s default timeout guard if no signal provided
  let timeoutId = null;
  if (!signal) {
    const controller = new AbortController();
    timeoutId = setTimeout(() => controller.abort(), 2500);
    signal = controller.signal;
  }

  const modelsToTry = model ? [model, ...GEMINI_MODELS.filter(m => m !== model)] : GEMINI_MODELS;
  let lastError = null;

  for (const currentModel of modelsToTry) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${currentModel}:generateContent?key=${apiKey}`;

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        signal,
        body: JSON.stringify({
          contents,
          systemInstruction: {
            parts: [{ text: customSystemPrompt || SYSTEM_PROMPT }]
          },
          generationConfig: {
            temperature: 0.7,
            topP: 0.95,
            maxOutputTokens: 1024
          }
        })
      });

      const data = await response.json();

      if (!response.ok) {
        if (
          data.error?.code === 400 && data.error?.message?.includes('API key not valid') ||
          data.error?.code === 403 ||
          data.error?.status === 'PERMISSION_DENIED'
        ) {
          isGeminiDisabled = true;
          console.warn('⚠️  [SpeedGuard] Gemini API key is invalid/blocked. Gemini engine auto-disabled for this session.');
          throw new Error('Invalid Gemini API Key');
        }
        if (data.error?.code === 404 || data.error?.status === 'NOT_FOUND') {
          lastError = new Error(data.error?.message || `Model ${currentModel} not found`);
          continue;
        }
        throw new Error(data.error?.message || `Gemini API HTTP Error ${response.status}`);
      }

      const candidate = data.candidates?.[0];
      const replyText = candidate?.content?.parts?.map(p => p.text).join('') || '';

      if (!replyText) {
        throw new Error('No response text generated by Gemini.');
      }

      return replyText;
    } catch (err) {
      if (err.name === 'AbortError') throw err;
      lastError = err;
    }
  }

  throw lastError || new Error('All Gemini models failed.');
}

/**
 * Generates an AI mentor response given message and previous chat history
 * @param {string} userMessage
 * @param {Array<{role: string, text: string}>} history
 * @param {Object} [userContext]
 */
async function getChatMentorReply(userMessage, history = [], userContext = null) {
  const contents = [];

  // Format history (last 6 messages for token efficiency & consistency)
  if (Array.isArray(history)) {
    for (const item of history.slice(-6)) {
      if (item.role && item.text) {
        contents.push({
          role: item.role === 'user' ? 'user' : 'model',
          parts: [{ text: item.text }]
        });
      }
    }
  }

  // Construct current prompt with optional student context
  let promptText = userMessage;
  if (userContext) {
    const contextLines = [];
    if (userContext.name) contextLines.push(`Student Name: ${userContext.name}`);
    if (userContext.degree) contextLines.push(`Degree: ${userContext.degree}`);
    if (userContext.targetCareer) contextLines.push(`Target Career: ${userContext.targetCareer}`);
    if (userContext.skills && userContext.skills.length) {
      contextLines.push(`Logged Skills: ${userContext.skills.join(', ')}`);
    }
    if (userContext.activeWeek) contextLines.push(`Current Roadmap Week: Week ${userContext.activeWeek}`);

    if (contextLines.length > 0) {
      promptText = `[Student Context: ${contextLines.join(' | ')}]\n\nStudent Query: ${userMessage}`;
    }
  }

  contents.push({
    role: 'user',
    parts: [{ text: promptText }]
  });

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 15000); // 15s timeout for Gemini fallback

  try {
    return await callGemini(contents, null, controller.signal);
  } finally {
    clearTimeout(timeoutId);
  }
}

module.exports = {
  getChatMentorReply,
  callGemini
};
