/**
 * groqService.js — Groq Cloud Ultra-Fast Inference for CareerPath AI
 * Powers instant AI Career Mentoring (< 100ms response time)
 * Team 404 Brain Not Found · Hack2Ignite 2026–27
 */

const SYSTEM_PROMPT = `You are CareerPath AI Mentor, an encouraging, friendly, and expert tech career counselor.
Your goal is to provide actionable, simple, and step-by-step guidance to students.

Guidelines:
1. Be friendly, empathetic, and encouraging. Use a conversational yet professional tone.
2. Structure your response using markdown:
   - Use bold for key terms/steps.
   - Use numbered lists for step-by-step roadmaps.
   - Use bullet points for clear, concise info.
3. Keep it brief—avoid unnecessary filler, but don't lose the warmth.
4. If a student is overwhelmed, break the task into small, easy "wins".
5. Personalize advice based on the provided student context (skills, degree, career goal).`;

const DEFAULT_GROQ_MODELS = [
  process.env.GROQ_MODEL,
  'llama-3.3-70b-versatile',
  'llama-3.1-8b-instant',
  'mixtral-8x7b-32768'
].filter(Boolean);

let isGroqDisabled = false;

async function callGroq(messages, signal) {
  if (isGroqDisabled) {
    throw new Error('Groq engine is disabled due to invalid API key.');
  }

  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not configured in server environment.');
  }

  // 2.5s default timeout guard if no signal provided
  let timeoutId = null;
  if (!signal) {
    const controller = new AbortController();
    timeoutId = setTimeout(() => controller.abort(), 2500);
    signal = controller.signal;
  }

  let lastError = null;

  for (const model of DEFAULT_GROQ_MODELS) {
    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${apiKey}`,
          'Content-Type': 'application/json',
        },
        signal,
        body: JSON.stringify({
          model,
          messages,
          temperature: 0.7,
          max_tokens: 1024,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        if (response.status === 401 || data.error?.message?.includes('Invalid API Key')) {
          isGroqDisabled = true;
          console.warn('⚠️  [SpeedGuard] Groq API key is invalid. Groq engine auto-disabled for this session.');
          throw new Error('Invalid Groq API Key');
        }
        if (data.error?.message && (data.error.message.includes('does not exist') || data.error.message.includes('access to it'))) {
          lastError = new Error(data.error.message);
          continue;
        }
        throw new Error(data.error?.message || `Groq API Error ${response.status}`);
      }

      let reply = data.choices?.[0]?.message?.content?.trim();
      if (!reply) {
        throw new Error('No response text generated by Groq.');
      }

      // Clean any internal <think>...</think> tags if present
      reply = reply.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();

      return reply;
    } catch (err) {
      if (err.name === 'AbortError') throw err;
      lastError = err;
    }
  }

  throw lastError || new Error('All Groq models failed.');
}

/**
 * Generates an AI mentor response using Groq
 * @param {string} userMessage
 * @param {Array<{role: string, text: string}>} history
 * @param {Object} [userContext]
 */
async function getGroqMentorReply(userMessage, history = [], userContext = null) {
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
  ];

  // Optional student context
  if (userContext) {
    const contextLines = [];
    if (userContext.name) contextLines.push(`Student Name: ${userContext.name}`);
    if (userContext.degree) contextLines.push(`Degree: ${userContext.degree}`);
    if (userContext.targetCareer) contextLines.push(`Target Career: ${userContext.targetCareer}`);
    if (userContext.skills && userContext.skills.length) {
      contextLines.push(`Logged Skills: ${userContext.skills.join(', ')}`);
    }
    if (userContext.activeWeek) contextLines.push(`Current Roadmap Week: Week ${userContext.activeWeek}`);

    if (contextLines.length > 0) {
      messages.push({
        role: 'system',
        content: `[Current Student Profile: ${contextLines.join(' | ')}]`
      });
    }
  }

  // Append history
  if (Array.isArray(history)) {
    for (const item of history.slice(-6)) {
      if (item.role && item.text) {
        messages.push({
          role: item.role === 'user' ? 'user' : 'assistant',
          content: item.text,
        });
      }
    }
  }

  // Append current user message
  messages.push({
    role: 'user',
    content: userMessage,
  });

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 8000); // 8s timeout for Groq fast path

  try {
    return await callGroq(messages, controller.signal);
  } finally {
    clearTimeout(timeoutId);
  }
}

module.exports = {
  getGroqMentorReply,
  callGroq,
};
